### ISSUE TITLE
Trying to add already registered factory

### ISSUE THREAD

**Issue by boris-petrov** [KengoTODA/spotbugs-gradle-plugin-v2#88] opened 2020-02-11 12:57 UTC
I get a bunch of these when running the new plugin (and I don't get them with the old one):

```
Trying to add already registered factory: SyncCollectionIterators, Plugin:com.mebigfatguy.fbcontrib
```

I get them for pretty much all SpotBugs plugins that I have. Any ideas?

P.S. I have a bunch of sourcesets that I check - it happens after a couple have already passed.

**Comment by boris-petrov** [comment] 2020-02-13 08:06
@KengoTODA - [here is a reproduction](https://github.com/boris-petrov/spotbugs-gradle-plugin-bug). Run `gradle spotbugsBackend` on this and see the errors.

**Comment by KengoTODA** [comment] 2020-02-16 22:34
Tried but could not reproduce. I have no Java13 so used `sourceCompatibility = JavaVersion.VERSION_11` instead. 

Note that SpotBugs does not work with Java 9+. I suggest you to use Java 8. 

```
$ ../spotbugs/gradlew -v

------------------------------------------------------------
Gradle 6.1
------------------------------------------------------------

Build time:   2020-01-15 23:56:46 UTC
Revision:     539d277fdba571ebcc9617a34329c83d7d2b259e

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          12.0.2 (AdoptOpenJDK 12.0.2+10)
OS:           Mac OS X 10.15.3 x86_64
```

**Comment by boris-petrov** [comment] 2020-02-17 08:47
@KengoTODA - that's funny, now it doesn't happen on this project for me either... but on my big project it does. Could [this](https://github.com/spotbugs/spotbugs/issues/819) be related?

As for SpotBugs on Java 9+ - I've been using it on Java 9, 10, 11, 12 and now 13 for years, not sure what you mean it doesn't work. :)

**Comment by KengoTODA** [comment] 2020-02-17 14:12
Ah, then it's nice... maybe you're not using buggy detectors. If you're interested in, see [issues tagged as Java9 issue](https://github.com/spotbugs/spotbugs/issues?q=is%3Aopen+is%3Aissue+label%3AJava-9) and others.

I think https://github.com/spotbugs/spotbugs/issues/819 is about the legacy plugin, and it's not related to this project. I'll close this issue but feel free to reopen when you could reproduce the problem. :+1:

**Closed as completed** 2020-02-17 14:12 UTC

**Comment by boris-petrov** [comment] 2020-02-19 08:52
@KengoTODA - I still believe this is an issue. I'm not getting these warnings with the old plugin but only with the new one... it *might* be an issue in SpotBugs itself, not sure, but I **am** seeing these warnings every time I run SpotBugs with the new plugin.
