### ISSUE TITLE
Extension Defaults

### ISSUE THREAD

**Issue by mistermage** [KengoTODA/spotbugs-gradle-plugin-v2#75] opened 2020-01-29 15:00 UTC
In the SpotBugsExtension constructor you have it setup like this:
```
@Inject
SpotBugsExtension(Project project, ObjectFactory objects) {
	(...)

	project.afterEvaluate( { p ->
		projectName.convention(p.getName());
		release.convention(p.getVersion().toString());
		reportsDir.convention(project.layout.buildDirectory.dir('reports/spotbugs'))
	});

	(...)
}
```

At the time I apply the plugin the project has already been evaluated though and I have to set those values manually. I also don't think that setup supports multi-module builds that use `allprojects{}` or `subprojects{}` to apply a common version.

I think a better setup would be something to the tune of:
```
@Inject
SpotBugsExtension(Project project, ObjectFactory objects) {
	(...)
	
	if (project.state.executed && project.rootProject.state.executed) {
		doTheThing()
	} else if (!project.rootProject.state.executed) {
		project.rootProject.afterEvaluate {
			doTheThing()
		}
	} else {
		project.afterEvaluate {
			doTheThing()
		}
	}
	
	(...)
}

void doTheThing() {
    projectName.convention(project.getName());
    release.convention(project.getVersion().toString());
    reportsDir.convention(project.layout.buildDirectory.dir('reports/spotbugs'))
}
```

**Comment by KengoTODA** [comment] 2020-01-30 08:12
refs https://github.com/gradle/gradle/issues/1135

**Comment by KengoTODA** [comment] 2020-01-30 08:40
Successfully reproduced this issue by the functional test 77a6db0 and 4c3efc0ee5f64b7b202af2e470b9555a5540b732.
But the suggested fix 732f959266ca56383fa522a6744d2eed38d5b4d1 does not work as expected, I will try to find another way.

**Comment by KengoTODA** [comment] 2020-01-30 11:01
### order to execute the build script

1. the root project is evaluated, and run `rootProject.afterEvaluate(action)`
2. `subproject {}` in the root project is evaluated, and `toolVersion` is set as `4.0.0-RC1`
3. the action set for the root project is executed
4. the subproject is evaluated, and run `subProject.afterEvaluate(action)`
5. the action set for the subproject is executed
6. `toolVersion` is resolved as `3.1.11` (default value)

### patch to debug

```diff
diff --git a/src/functionalTest/groovy/com/github/spotbugs/snom/MultiProjectFunctionalTest.groovy b/src/functionalTest/groovy/com/github/spotbugs/snom/MultiProjectFunctionalTest.groovy
index 04ed5a8..da25cd7 100644
--- a/src/functionalTest/groovy/com/github/spotbugs/snom/MultiProjectFunctionalTest.groovy
+++ b/src/functionalTest/groovy/com/github/spotbugs/snom/MultiProjectFunctionalTest.groovy
@@ -105,6 +105,7 @@ repositories {
         setup:
         buildFile << """
 subprojects {
+    println '<<< configure extension in subprojects'
     spotbugs {
         toolVersion = '4.0.0-RC1'
     }
diff --git a/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy b/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
index 2cf49e6..90463ad 100644
--- a/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
+++ b/src/main/groovy/com/github/spotbugs/snom/SpotBugsExtension.groovy
@@ -143,6 +143,7 @@ class SpotBugsExtension {
 
     @Inject
     SpotBugsExtension(Project project, ObjectFactory objects) {
+        println "<<< created an extension for ${project.name}"
         ignoreFailures = objects.property(Boolean).convention(false);
         showProgress = objects.property(Boolean);
         reportLevel = objects.property(Confidence);
@@ -156,6 +157,7 @@ class SpotBugsExtension {
         projectName = objects.property(String);
         release = objects.property(String);
         configureFromProject(project, { p ->
+            println "<<< configure the extension for project ${p.name}"
             projectName.convention(p.getName())
             release.convention(p.getVersion().toString())
             reportsDir.convention(project.layout.buildDirectory.dir('reports/spotbugs'))
@@ -178,10 +180,13 @@ class SpotBugsExtension {
 
     private void configureFromProject(Project project, Action<Project> action) {
         if (project.state.executed && project.rootProject.state.executed) {
+            println "<<< 1"
             action.execute project
         } else if (!project.rootProject.state.executed) {
+            println "<<< 2 ${project.name}"
             project.rootProject.afterEvaluate action
         } else {
+            println "<<< 3 ${project.name}"
             project.afterEvaluate action
         }
     }
diff --git a/src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java b/src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java
index 766c2fc..a37357c 100644
--- a/src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java
+++ b/src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java
@@ -71,11 +71,12 @@ public class SpotBugsPlugin implements Plugin<Project> {
             .setTransitive(true);
 
     configuration.defaultDependencies(
-        (DependencySet dependencies) ->
+        (DependencySet dependencies) -> {
+                System.out.printf("<<<  toolversion for %s is %s%n", project.getName(), extension.getToolVersion().get());
             dependencies.add(
                 project
                     .getDependencies()
-                    .create("com.github.spotbugs:spotbugs:" + extension.getToolVersion().get())));
+                    .create("com.github.spotbugs:spotbugs:" + extension.getToolVersion().get()));});
 
     Configuration spotbugsSlf4j =
         project
```

**Comment by KengoTODA** [comment] 2020-01-30 12:54
> I also don't think that setup supports multi-module builds that use allprojects{} or subprojects{} to apply a common version.

I found that the official plugins like `pmd` has the same problem. Even though we configure extension in `subprojects` block, it is not reflected to the build. I think it comes from limitation of Gradle itself.

> At the time I apply the plugin the project has already been evaluated though and I have to set those values manually.

I'm afraid that I haven't reproduced this issue by functional tests such as 77a6db0 and 4c3efc0. @mistermage Could you share [an MCVE](https://stackoverflow.com/help/minimal-reproducible-example) with us? Just share two `build.gradle` files should be enough.

**Comment by mistermage** [comment] 2020-01-31 15:08
@KengoTODA I am looking into making the example now

**Comment by mistermage** [comment] 2020-01-31 15:39
@KengoTODA 

I found an interesting issue when attempting to make the simple example:

**build.gradle**
```
plugins {
	id 'java'
	id "jp.skypencil.spotbugs.snom" version "0.4.17"
}

dependencies {
	testImplementation group: 'junit', name: 'junit', version: '4.12'
}
```
with this folder structure:
```
|   build.gradle
|   gradlew
|   gradlew.bat
|   settings.gradle
|
+---gradle
|   \---wrapper
|           gradle-wrapper.jar
|           gradle-wrapper.properties
|
\---src
    +---main
    |   \---java
    |       \---package
    |           	SimpleLibrary.java
    |
    +---sandbox
    |   \---java
    |       \---package
    |           	DoAThing.java
    |
    \---test
        \---java
            \---package
                	SimpleLibraryTest.java
```

And the plugin doesn't create any tasks. It does create configurations but at the time it's supposed to create the tasks it sees that it doesn't have any source sets (which is incorrect).

Is there a reason why you strayed away from using the `AbstractCodeQualityPlugin` from Gradle? I attempted the same with the 'v1' of the spotbugs plugin and it works just fine.

Gradle Version: 6.0.1

**Comment by KengoTODA** [comment] 2020-02-01 06:40
> Is there a reason why you strayed away from using the AbstractCodeQualityPlugin from Gradle?

The [AbstractCodeQualityPlugin](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java) is Gradle's internal API (see its package name) so we have strong motivation to avoid.
The legacy implementation forked from official FindBugs plugin depends on internal APIs so its maintenance is super troublesome. 😭

> And the plugin doesn't create any tasks. 

I cannot reproduce this issue. Do you mean the task for `sandbox` source set? Then I think you need to add `sourceSets { sandbox { ... } }` to your build script.

**Comment by slamdev** [comment] 2020-02-02 20:14
@KengoTODA I have the same issue as @mistermage :
```bash
$ ls -a
.		..		.gradle		build.gradle
$ cat build.gradle
plugins {
    id 'java'
    id "jp.skypencil.spotbugs.snom" version "0.4.17"
}
$ gradle spotbugsMain

FAILURE: Build failed with an exception.

* What went wrong:
Task 'spotbugsMain' not found in root project 'test123'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 449ms
```
although the task exists if this build.gradle file is used:
```groovy
buildscript {
   repositories {
       maven {
           url "https://plugins.gradle.org/m2/"
       }
   }
   dependencies {
       classpath "gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin-v2:0.4.17"
   }
}


plugins {
    id 'java'
}
apply plugin: "jp.skypencil.spotbugs.snom"
```

**Comment by KengoTODA** [comment] 2020-02-03 07:55
@slamdev you have no sourceSet actually, right? I cannot find `src` directory in the project.

**Comment by KengoTODA** [comment] 2020-02-03 10:12
It is possible that we need to ensure that the java-base plugin is applied before this plugin. In case of the legacy impl, we have a code at here:

https://github.com/gradle/gradle/blob/52d0d7509bef337f20bb9bfc6a1a3bbce35ad226/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java#L135

**Comment by KengoTODA** [comment] 2020-02-03 14:09
@slamdev #83 fixed your issue, please try version `0.4.19`.

@mistermage is there any unfixed issue? If not, I will merge #78 and close this issue. Thanks!

**Comment by mistermage** [comment] 2020-02-03 14:24
@KengoTODA Sorry for the delay in my responses; I will also try out `0.4.19` and see if my issues are resolved. If not I will try to make the sample project again! Thank you for your quick responses so far though.

**Comment by KengoTODA** [comment] 2020-02-03 14:53
@mistermage OK then I will merge #78 first, and release `0.4.20`. Please use it instead.

**Comment by KengoTODA** [comment] 2020-02-03 15:03
If we still have problem, please create new issue instead of this closed one.

**Closed as completed** 2020-02-03 15:03 UTC
Labels: bug, released
